# Generated by Django 4.1.7 on 2023-03-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_notes',
        ),
        migrations.AddField(
            model_name='property_info',
            name='property_notes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
