# Generated by Django 4.1.7 on 2023-03-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_remove_property_property_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField()),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.property')),
            ],
        ),
    ]
