# Generated by Django 4.1.7 on 2023-03-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='run_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
