# Generated by Django 4.1.7 on 2023-03-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_history_run_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_info',
            name='motopress_rates_request',
            field=models.CharField(default='motoseasonrequest.com/season/', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_info',
            name='motopress_season_request',
            field=models.CharField(default='motoratesrequest.com/rates/', max_length=200),
            preserve_default=False,
        ),
    ]
