# Generated by Django 4.1.7 on 2023-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_history_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='notes',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
