# Generated by Django 4.1.7 on 2024-07-14 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_history_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSyncInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_login', models.CharField(max_length=500)),
                ('sync_url', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.property')),
            ],
        ),
    ]
