# Generated by Django 4.1.7 on 2025-06-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_calendarsyncinfo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['property_name', 'run_date'], name='integration_propert_8613f2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['user', 'property_name'], name='integration_user_id_4780bc_idx'),
        ),
    ]
